### ISSUE TITLE
Build Failure due to Warnings

### ISSUE THREAD

**Issue by Mikilio** [exeldro/obs-source-clone#22]
obs-studio has deprecated some functions this plugin is using.
see: [obs-studio](https://github.com/obsproject/obs-studio/issues/10397)

**Comment by exeldro** [comment]
That looks like you did not update your source clone because it should be fixed in https://github.com/exeldro/obs-source-clone/commit/c22a6f3a62ef33d5d4b90a72ae0ed24722f2c908
