### ISSUE TITLE
Query on large source clones?

### ISSUE THREAD

**Issue by talkiet** [exeldro/obs-source-clone#28]
Using a network SRT Media source from a remote machine (triple screen iRacing @ 7680x1440), I seem to have found an issue which may lie in source clone.
I receive the 7680x1440 media source, and then create 2 source clones of it. One is for the left screen and one for the right. I attempt to trim these down by cropping them down, but it seems that the source clones are only 1920x1080 as far as the crop/pad filter or the Transform/Edit transform box are concerned. If I trim 2560 off the left, then the soruce clone becomes empty. IF however I trim 640 off, then that slices off the left 1/3 of the image.
Is source clone maxed at 1920x1080?

**Comment by exeldro** [comment]
I tested it with OBS 30.2.2, source clone 0.1.5 and an image source of 7680x1440 cloned that and tried crop in the transform and as crop filter, both worked fine for me. 
![image](https://github.com/user-attachments/assets/4cad7d5e-dced-4ecf-b6a5-f7146e6c8981)
Can you provide video or screenshots of the issue?

**Comment by talkiet** [comment]
Thanks... You can close this one as no fault found :-) Or idiot user missed a setting. Your pick! It works great now - the only issue is the second PC has nowhere near enough power to composite and encode the silly multimonitor stream but I don't expect you to solve that as well. Thanks for the sanity check forcing me to actually look at all my settings!
