### ISSUE TITLE
[FEAT] Adding Flatpak

### ISSUE THREAD

**Issue by G4PLS** [exeldro/obs-source-clone#29]
Im on Linux and I use the Flatpak version of OBS, in there you cant use Custom Plugins anymore so you have to install them via flatpak.

Its already setup for obs-move-transition and it would be awesome if source clone could also be setup via flatpak

**Comment by tinyplayerss** [comment]
I get my flatpak obs plugins from Software Manager on Linux Mint 22 And it would be Really Great if theres a Flatpak build of the Plugin to be available on the Software manager for the flatpak version of OBS!

**Comment by exeldro** [comment]
Added now

**Comment by polluxau** [comment]
> Added now

Wow that was fast, thank you so much we all rlly appreciate it :)
