### ISSUE TITLE
Cloned source does not trigger InputActiveStateChanged websocket event

### ISSUE THREAD

**Issue by ZeAntwan** [exeldro/obs-source-clone#6]
A bit of a request and "bug" at the same time.

To give some context, I'm using Source Clone as a mean to create a layout in OBS and easily swap cameras in them without having to copy a source around.
Something else I'm also making is a Tally system that listen to websocket events and check if they are live, or on preview.

Unfortunately, when turn on or off the Source Clone, the "Source Clone" source fires both InputActiveStateChanged and InputShowStateChanged as expected, but only the InputShowStateChanged gets trigged for the cloned source.

![image](https://user-images.githubusercontent.com/11023019/218266729-78d36997-ddc0-423d-a56c-36e6414a4c15.png)

**Comment by exeldro** [comment]
Do you have the "Active Clone" option enabled?

**Comment by ZeAntwan** [comment]
I did not, and enabling the option fixed it! Sorry for that! Didn't know what the "Active Clone" option was for. Thanks!
